--- #YAML:1.0
name:                MMapDB
version:             0.10
abstract:            a simple database in shared memory
license:             ~
author:              
    - Torsten Foertsch <torsten.foertsch@gmx.net>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    File::Map:                     0.16
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
